version: '3.0'

services:
  web_apps:
      container_name: web_apps
      restart: always
      image: tomcat
      volumes:
         - './web_apps/:/usr/local/tomcat/webapps' #letak direktori aplikasi dan target directory yang ada di container
         - './jdbc.properties:/Applications/NetBeans/glassfish-4.1.1/configuration/jdbc.properties'
         - './urls.properties:/Applications/NetBeans/glassfish-4.1.1/configuration/urls.properties'
         - '/etc/localtime:/etc/localtime:ro'
      ports:
         - "8080:8080"
  python:
      container_name: python
      build: ./python_build
      restart: always
      image: python_build
      volumes:
         - './python/:/usr/src/app'
         - '/etc/localtime:/etc/localtime:ro'
      ports:
         - "5000:5000"                           #sesuaikan port dengan listener port applikasi
      command: python /usr/src/app/fm_face_recognition.py
  tunnel:
      container_name: tunnel
      build: ./tunnel_build
      restart: always
      image: tunnel
      volumes:
         - './tunnel_account/:/tunnel/'
      command: openvpn /tunnel/BSD.ovpn
      devices:
         - /dev/net/tun:/dev/net/tun
